### ISSUE TITLE
Add a cover

### ISSUE THREAD

**Issue by hammer** [hammerlab/learning-about-t-cells-through-data#7]
I made a quick one w/ Canva:

![cover](https://user-images.githubusercontent.com/15233/45630625-0dc1c280-ba67-11e8-9539-b38391d7e5eb.png)

However, when I put this into the repo under `images/cover.png` and add `cover-image: images/cover.png` to the `index.Rmd` YAML header, nothing happens. I've wasted an hour on this task and need to move on so will come back to it later.

**Comment by hammer** [comment]
Filed https://github.com/rstudio/bookdown/issues/634 to hopefully get more information on how to handle this case.

**Comment by armish** [comment]
Ahem...
![tcell-bigdata](https://user-images.githubusercontent.com/7809/45632162-ab6ac100-ba6a-11e8-9b53-f2b1a4264706.png)

**Comment by hammer** [comment]
Closed w/ 5858d7e6fde9d4fcc484da4c795a64a06ac9d73a
